### ISSUE TITLE
EXC_BAD_ACCESS: pointer being freed was not allocated

### ISSUE THREAD

**Issue by Kerollmops** [RedisLabsModules/redismodule-rs#35] opened 2019-09-07 17:34 UTC
Currently the `RedisAlloc` is [enforced at compilation](https://github.com/RedisLabsModules/redismodule-rs/blob/4f7a37849951ee2df9f9443dc519e7a3f3fca505/src/lib.rs#L31-L32) and then [at runtime a flag is used](https://github.com/RedisLabsModules/redismodule-rs/blob/4f7a37849951ee2df9f9443dc519e7a3f3fca505/src/alloc.rs#L29-L32) to [enabled the allocator or not](https://github.com/RedisLabsModules/redismodule-rs/blob/4f7a37849951ee2df9f9443dc519e7a3f3fca505/src/alloc.rs#L13-L14).

The first problem is that if the application do not want to use it it is currently not possible as [it is always enabled in the macro](https://github.com/RedisLabsModules/redismodule-rs/blob/4f7a37849951ee2df9f9443dc519e7a3f3fca505/src/macros.rs#L96-L100).

The second problem is that the global allocator is enforced and even if the `use_redis_alloc` function is not called the allocator will fallback on the `System` allocator, therefore it is not possible to use, for example, the jemalloc one (which can be way more performant than the system's one).

The third and last problem is that I faced `BAD_ACCESS` crashes that were triggered [inside the `RedisAlloc::dealloc` function](https://github.com/RedisLabsModules/redismodule-rs/blob/4f7a37849951ee2df9f9443dc519e7a3f3fca505/src/alloc.rs#L23) of the kind: "pointer used after being freed". I think about it and it was probably because the `USE_REDIS_ALLOC` static was enabled *after* some `alloc` calls were already made to the allocator and therefore [allocations were made by the system's one](https://github.com/RedisLabsModules/redismodule-rs/blob/4f7a37849951ee2df9f9443dc519e7a3f3fca505/src/alloc.rs#L17) but [freed by the redis one](https://github.com/RedisLabsModules/redismodule-rs/blob/4f7a37849951ee2df9f9443dc519e7a3f3fca505/src/alloc.rs#L23).

One solution could have been to enforce the allocator only when a specific feature is set and do not rely on a secondary runtime setting (i.e. the flag) to enable or disable the allocator, it is dangerous.

```toml
# Cargo.toml
[features]
default = ["redis-allocator"]
experimental-api = []
redis-allocator = []
```

```rust
// lib.rs
#[cfg_attr(feature="redis-allocator", global_allocator)]
static ALLOC: crate::alloc::RedisAlloc = crate::alloc::RedisAlloc;
```

By the way I did not take the time to look at what does declaring a `global_allocator` do in a library, wasn't it made to be used in a binary project? What happen if I declare another `global_allocator` inside my `main.rs` file?

**Comment by Kerollmops** [comment] 2019-09-08 09:40
I just hit the "used after freed" error and it did not comes from the `RedisAlloc` type.

```
redis-server(31485,0x70000428f000) malloc: Incorrect checksum for freed object 0x7f851e819a50: probably modified after being freed.
Corrupt value: 0x6fffffff74cb5e00
redis-server(31485,0x70000428f000) malloc: *** set a breakpoint in malloc_error_break to debug
./run-redis-server.sh: line 11: 31485 Abort trap: 6           redis-server --loadmodule ./target/debug/libspo2.dylib
```

**Comment by gavrie** [comment] 2019-09-11 11:47
@Kerollmops thanks for the detailed report!

Regarding the use of a feature to enable the Redis allocator: That's a good idea; I'll look at it.

Regarding the use of the `System` allocator fallback: Good point; I agree that it it should fall back to the Global allocator and not the system one.

Regarding the crash:

A while ago, I also encountered a crash related to the allocator. It seems similar, but I haven't dived into the details of your crash yet. It was related to the use of `std::io` (via `println!`) before switching the allocator to the Redis one; I guess there is something in the `std::io` implementation that allocates an internal buffer or such that can be `realloc`d at a later stage.

What I did to solve it is make sure that no `std::io` calls were performed before switching the allocator. This was fixed by 2c37545 and 08d8fbc. 

Does your crash still happen with current `master`?

**Comment by gavrie** [comment] 2019-09-11 13:02
@Kerollmops Update: It seems like your version already included these commits, so that may not be the root cause.

**Comment by Kerollmops** [comment] 2019-09-13 07:03
Thank you for the reply,

I do not think it would be possible to fallback on the global allocator as it is `RedisAlloc` once declared.

Notice that the crash is not related to the allocator in any way because I disabled it on my repository.

**Comment by gavrie** [comment] 2020-04-07 18:58
Due to the recent changes (#68) this is probably no longer relevant so I'm closing it.
Please reopen if it is still relevant.

**Closed by gavrie** 2020-04-07 18:58 UTC
